ViridianForestDepths_Text_TreeckoNoise::
    .string "Trrrrrrrrrk!!$"

ViridianForestDepths_Text_TreeckoStuck::
    .string "This TREECKO is looking terrified\n"
    .string "and all alone.\p"
	.string "It's looking at you with its,\n"
	.string "big, yellow eyes…\p"
	.string "This POKéMON seems to trust\n"
	.string "you completely.\p"
	.string "Do you want to take it with you?$"

ViridianForestDepths_Text_TreeckoSaved::
    .string "TREECKO looks very glad.$"

ViridianForestDepths_Text_ObtainedTreecko::
    .string "{PLAYER} obtained a TREECKO!$"
