ViridianForestDepths_Text_WelcomeSign1::
    .string "VIRIDIAN FOREST GROVE\p"
    .string "Beware of GHOST POKéMON!$"

ViridianForestDepths_Text_WelcomeSign2::
    .string "VIRIDIAN FOREST GROVE\n"
    .string "Burial ground ahead$"

ViridianForestDepths_Text_GraveSign::
    .string "VIRIDIAN FOREST BURIAL GROUND$"
	
ViridianForestDepths_Text_GraveTextSign::
    .string "This burial ground houses the\n"
    .string "remains of the great HERO,\p"
	.string "who protected VIRIDIAN against\n"
	.string "the invading forces of JOHTO.\p"
	.string "May he and his POKéMON rest\n"
	.string "in peace.$"

ViridianForestDepths_Text_TreeckoNoise::
    .string "Trrrrrrrrrk!!$"

ViridianForestDepths_Text_TreeckoStuck::
    .string "This TREECKO is looking terrified\n"
    .string "and all alone…\p"
	.string "It's taking you in with its big,\n"
	.string "yellow eyes…\p"
	.string "The POKéMON has decided to trust\n"
	.string "you without hesitation.\p"
	.string "Do you want to take it with you?$"
	
ViridianForestDepths_Text_TreeckoSad::
	.string "TREECKO looks like it's about\n"
	.string "to cry…$"

ViridianForestDepths_Text_TreeckoHappy::
    .string "TREECKO jumps up and down\n"
	.string "happily!$"

ViridianForestDepths_Text_ObtainedTreecko::
    .string "{PLAYER} obtained a TREECKO!$"
