ThreeIsland_DunsparceTunnel_Text_ProspectingForGold:: @ 817D13B
    .string "Hey, there!\n"
    .string "How's it going?\p"
    .string "What am I doing here, you ask?\n"
    .string "Why, I'm prospecting for gold!\p"
    .string "When I strike it rich, I'm buying\n"
    .string "a house in KANTO.$"

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou:: @ 817D1C9
    .string "Hey, there! How's it going?\n"
    .string "Did you hear? I've struck gold!\p"
    .string "You remembered that I was\n"
    .string "prospecting, didn't you?\p"
    .string "You can't begin to imagine just\n"
    .string "how happy I am.\p"
    .string "I also found something peculiar\n"
    .string "while digging through here.\p"
    .string "I'm feeling generous now that\n"
    .string "I'm rich, so this is for you!$"

ThreeIsland_DunsparceTunnel_Text_ThatsANugget:: @ 817D28C
    .string "That's a {STR_VAR_1}!\p"
    .string "I can't give you any of its ancient\n"
    .string "wisdom, so that'll have to do!$"

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull:: @ 817D2DC
    .string "Whoops, your BAG is crammed full!\n"
    .string "I'll give this to you later.$"

ThreeIsland_DunsparceTunnel_Text_ObtainedFossil::
    .string "{PLAYER} received a {STR_VAR_1}\nfrom the prospector!$"
