Route5_Text_UndergroundPathSign:: @ 8183DD4
    .string "UNDERGROUND PATH\n"
    .string "CERULEAN CITY - VERMILION CITY$"

Route5_Text_Burglar::
    .string "What do you want?\n"
    .string "Can't you see I'm busy?\p"
	.string "You're gonna snitch on me,\n"
	.string "aren't you?!\p"
	.string "I'll make sure that won't happen!$"
	
Route5_Text_BurglarDefeat::
	.string "Darn it!!\n"
	.string "It's over for me!$"
	
Route5_Text_BurglarHaveChikorita::
	.string "I lost to a darn kid!\n"
	.string "It's over for me!\p"
	.string "Unless… Wait!\n"
	.string "I have something for you!\p"
	.string "Promise to let me go and you\n"
	.string "can have it!$"
	
Route5_Text_ObtainedChikorita::
	.string "{PLAYER} obtained a CHIKORITA\n"
	.string "from the shady BURGLAR!$"
	
Route5_Text_BurglarGottaGo::
	.string "You got your prize, so now you\n"
	.string "you can leave me in peace.\p"
	.string "Tschüss!$"