PewterCity_Museum_B1F_Text_HikerExplains::
    .string "Welcome to the UNDERGROUND\n"
	.string "CHALLENGE!\p"
	.string "In this darkened room, your task is\n"
	.string "to reach the end, where a radiant\p"
	.string "prize awaits you!\p"
	.string "If you aren't up to the task,\n"
	.string "return back to the surface.\p"
	.string "If you are, good luck!$"

PewterCity_Museum_B1F_Text_Scientist::
    .string "How are you liking our little\n"
	.string "UNDERGROUND CHALLENGE?\p"
	.string "We wanted to let our visitors feel\n"
    .string "the excitement of spelunking and\p"
	.string "exploring the various caverns of\n"
	.string "the KANTO region.$"

PewterCity_Museum_B1F_Text_YouEarnedFlash::
    .string "Congratulations!\p"
	.string "You managed to reach the end of our\n"
	.string "UNDERGROUND CHALLENGE!\p"
    .string "You've earned this.\n"
	.string "Here you go!$"

PewterCity_Museum_B1F_Text_ReceivedHM05FromScientist::
    .string "{PLAYER} received HM05\n"
    .string "from the SCIENTIST.$"

PewterCity_Museum_B1F_Text_ExplainHM05::
    .string "HM05 contains the hidden move\n"
    .string "FLASH.\p"
    .string "FLASH lights up even the darkest\n"
    .string "of caves and dungeons.\p"
	.string "Feel free to try it out!$"