ViridianCity_NewHouse_Text_ImFishingGuruDoYouLikeToFish::
    .string "I'm the FISHING GURU!\p"
    .string "I simply looove fishing!\n"
    .string "I can't bear to go without.\p"
    .string "Tell me, do you like to fish?$"

ViridianCity_NewHouse_Text_TakeThisAndFish::
    .string "Grand! I like your style.\n"
    .string "I think we can be friends.\p"
    .string "Take this and fish, young friend!$"

ViridianCity_NewHouse_Text_ReceivedOldRodFromFishingGuru::
    .string "{PLAYER} received an OLD ROD from\n"
    .string "the FISHING GURU.$"

ViridianCity_NewHouse_Text_FishingIsAWayOfLife::
    .string "Fishing is a way of life!\n"
    .string "It is like the finest poetry.\p"
    .string "From the seas to rivers, go out\n"
    .string "and land the big one, my friend.$"

ViridianCity_NewHouse_Text_OhThatsSoDisappointing::
    .string "Oh…\n"
    .string "That's so disappointing…$"

ViridianCity_NewHouse_Text_HowAreTheFishBiting::
    .string "Hello there, {PLAYER}!\p"
    .string "How are the fish biting?$"

ViridianCity_NewHouse_Text_NoRoomForNiceGift::
    .string "Oh, no!\p"
    .string "I had a nice gift for you, but you\n"
    .string "have no room for it!$"

