#ifndef GUARD_CONSTANTS_TRAINER_FAN_CLUB_H
#define GUARD_CONSTANTS_TRAINER_FAN_CLUB_H

#define FANCLUB_MEMBER1        0
#define FANCLUB_MEMBER2        1
#define FANCLUB_MEMBER3        2
#define FANCLUB_MEMBER4        3
#define FANCLUB_MEMBER5        4
#define FANCLUB_MEMBER6        5
#define FANCLUB_MEMBER7        6
#define FANCLUB_MEMBER8        7

#define FANCOUNTER_DEFEATED_DRAKE    0
#define FANCOUNTER_BATTLED_AT_BASE   1
#define FANCOUNTER_FINISHED_CONTEST  2
#define FANCOUNTER_USED_BATTLE_TOWER 3

#define NUM_TRAINER_FAN_CLUB_MEMBERS  8

#endif //GUARD_CONSTANTS_TRAINER_FAN_CLUB_H
