@ The text here is a copy/paste from Hoenn's Safari Zone, and any unused text was left untranslated

SafariZone_Text_WouldYouLikeToExit:: @ 81BFBE9
	.string "Would you like to exit the SAFARI\n"
	.string "ZONE right now?$"

SafariZone_Text_TimesUp:: @ 81BFC1B
	.string "PA: Ding-dong!\p"
	.string "Time's up!\p"
	.string "PA: Your SAFARI GAME is over!$"

SafariZone_Text_OutOfBalls:: @ 81BFC53
	.string "PA: Ding-dong!\p"
	.string "You are out of SAFARI BALLS!\p"
	.string "PA: Your SAFARI GAME is over!$"

SafariZone_Text_ExcuseMeYourPCBoxIsFull:: @ 81BFEAC
	.string "Excuse me!\n"
	.string "Your PC BOX is full.$"

