FuchsiaCity_House2_Text_HaveMonForExisting:: @ 8176266
    .string "You look like a fan of rare POKéMON.\n"
    .string "You should have this LAPRAS.$"

FuchsiaCity_House2_Text_ObtainedLaprasFromScientist:: @ 81762D7
    .string "{PLAYER} obtained a LAPRAS!$"

FuchsiaCity_House2_Text_ExplainLapras:: @ 8176305
    .string "LAPRAS can ferry you across seas and\n"
    .string "use attacks like ICE BEAM!\p"
    .string "I hope you will take good care\n"
    .string "of this intelligent POKéMON.$"

FuchsiaCity_House2_Text_HowIsLapras::
    .string "Hello again! How is LAPRAS…\n"
    .string "faring?\p"
    .string "Hahah, I know, I know!\p"
    .string "That was a horrible pun.$"