Route21_North_Text_RonaldIntro::
	.string "You want to know if the fish are\n"
	.string "biting?$"

Route21_North_Text_RonaldDefeat::
	.string "Dang!$"

Route21_North_Text_RonaldPostBattle::
	.string "I can't catch anything good.\n"
	.string "Not one good POKéMON to be had!$"

Route21_North_Text_WadeIntro::
	.string "I got a big haul!\n"
	.string "Wanna go for it?$"

Route21_North_Text_WadeDefeat::
	.string "Heheh, MAGIKARP just don't make\n"
	.string "the grade, do they?$"

Route21_North_Text_WadePostBattle::
	.string "I seem to only catch MAGIKARP!$"

Route21_North_Text_SpencerIntro::
	.string "The sea cleanses my body and soul!$"

Route21_North_Text_SpencerDefeat::
	.string "Ayah!$"

Route21_North_Text_SpencerPostBattle::
	.string "The sea is great and all, but I\n"
	.string "like the mountains, too.$"
