ViridianForest_Text_FriendsItchingToBattle:: @ 8172255
    .string "I came here with some friends to\n"
    .string "catch us some BUG POKéMON!\p"
    .string "They're all itching to get into\n"
    .string "some POKéMON battles!$"

ViridianForest_Text_RickIntro:: @ 81722C7
    .string "Hey! You have POKéMON!\n"
    .string "Come on!\l"
    .string "Let's battle 'em!$"

ViridianForest_Text_RickDefeat:: @ 81722F9
    .string "No!\nCATERPIE can't hack it!$"

ViridianForest_Text_RickPostBattle:: @ 8172315
    .string "Ssh! You'll scare the bugs away.\n"
    .string "Another time, okay?$"

ViridianForest_Text_DougIntro:: @ 817234A
    .string "Yo!\n"
    .string "You can't jam out if you're a\l"
    .string "POKéMON TRAINER!$"

ViridianForest_Text_DougDefeat:: @ 817237D
    .string "Huh?\n"
    .string "I ran out of POKéMON!$"

ViridianForest_Text_DougPostBattle:: @ 8172398
    .string "That totally stinks! I'm going to\n"
    .string "catch some stronger ones!$"

ViridianForest_Text_SammyIntro:: @ 81723D4
    .string "Hey, wait up!\n"
    .string "What's the hurry? Why the rush?$"

ViridianForest_Text_SammyDefeat:: @ 8172402
    .string "I give!\n"
    .string "You're good at this!$"

ViridianForest_Text_SammyPostBattle:: @ 817241F
    .string "Sometimes, you can find stuff on\n"
    .string "the ground.\p"
    .string "I'm looking for the stuff I\n"
    .string "dropped. Can you help me?$"

ViridianForest_Text_AnthonyIntro:: @ 8172482
    .string "I might be little, but I won't like\n"
    .string "it if you go easy on me!$"

ViridianForest_Text_AnthonyDefeat:: @ 81724BF
    .string "Oh, boo.\n"
    .string "Nothing went right.$"

ViridianForest_Text_AnthonyPostBattle:: @ 81724DC
    .string "I lost some of my allowance…$"

ViridianForest_Text_CharlieIntro:: @ 81724F9
    .string "Did you know that POKéMON evolve?$"

ViridianForest_Text_CharlieDefeat:: @ 817251B
    .string "Oh!\n"
    .string "I lost!$"

ViridianForest_Text_CharliePostBattle:: @ 8172527
    .string "BUG POKéMON evolve quickly.\n"
    .string "They're a lot of fun!$"

ViridianForest_Text_RanOutOfPokeBalls:: @ 8172559
    .string "I was throwing POKé BALLS to\n"
    .string "catch POKéMON, and I ran out.\p"
    .string "That's why you can never have too\n"
    .string "many POKé BALLS.$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak:: @ 81725C7
    .string "TRAINER TIPS\p"
    .string "If your POKéMON are weak and you\n"
    .string "want to avoid battles, stay away\l"
    .string "from grassy areas!$"

ViridianForest_Text_UseAntidoteForPoison:: @ 8172629
    .string "For poison, use ANTIDOTE!\n"
    .string "Get it at POKéMON MARTS!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex:: @ 817265C
    .string "TRAINER TIPS\p"
    .string "Contact PROF. OAK via a PC to\n"
    .string "get your POKéDEX evaluated!$"

ViridianForest_Text_CantCatchOwnedMons:: @ 81726A3
    .string "TRAINER TIPS\p"
    .string "You can't catch a POKéMON that\n"
    .string "belongs to someone else.\p"
    .string "Throw POKé BALLS only at wild\n"
    .string "POKéMON to catch them!$"

ViridianForest_Text_WeakenMonsBeforeCapture:: @ 817271D
    .string "TRAINER TIPS\p"
    .string "Weaken POKéMON before attempting\n"
    .string "capture!\p"
    .string "When healthy, they may escape!$"

ViridianForest_Text_LeavingViridianForest:: @ 8172773
    .string "LEAVING VIRIDIAN FOREST\n"
    .string "PEWTER CITY AHEAD$"
	
ViridianForest_Text_TorchicNoise::
    .string "Chiiiiic!!$"

ViridianForest_Text_TorchicScared::
    .string "The TORCHIC looks\n"
    .string "very scared!$"

ViridianForest_Text_TorchicSaved::
    .string "TORCHIC looks relieved.\p"
    .string "It seems to want to join you!\p"
	.string "Do you want to bring TORCHIC\p"
	.string "along?$"

ViridianForest_Text_ObtainedTorchic::
    .string "{PLAYER} obtained a TORCHIC!$"

ViridianForest_Text_Grunt::
    .string "And you are?\p"
	.string "Yes, I'm trying to get this stupid\n"
	.string "thing to listen.\p"
	.string "Is that so bad?\p"
	.string "W-wait, it's my POKéMON.\p"
	.string "I can do whatever I want with it!\p"
	.string "I really think you need to be\n"
	.string "taught a lesson.\p"
	.string "I will teach you not to mess\n"
	.string "with TEAM ROCKET!$"
	

ViridianForest_Text_GruntDefeat::
    .string "Okay, okay! Whatever!$"

ViridianForest_Text_GruntLeave::
	.string "You know what?\p"
	.string "You can keep the stupid POKéMON,\n"
	.string "I will just catch a new one!\p"
	.string "Whahaha!$"