SevenIsland_House_Room1_Text_OnlyEnjoymentWatchingBattles:: @ 81A049B
    .string "I may not look like much now,\n"
    .string "but when I was younger…\p"
    .string "I flew everywhere, challenging\n"
    .string "TRAINERS wherever I found them.\p"
    .string "Now, my only source of enjoyment\n"
    .string "is reminiscing about the past while\l"
    .string "watching tough TRAINERS battle.\p"
    .string "Wait, those BADGES…\n"
    .string "You've beaten the GYMS of KANTO?\l"
    .string "Funny, you don't look like much.\p"
    .string "But, then, you must know many\n"
    .string "tough TRAINERS from your travels.\p"
    .string "Can you stay a while and tell\n"
    .string "a bored old woman about them?$"

SevenIsland_House_Room1_Text_ShowFameChecker::
    .string "Show her the FAME CHECKER?$"

SevenIsland_House_Room1_Text_NoShowFameChecker::
    .string "I see…\n"
    .string "Well, go on with your travels then…$"

SevenIsland_House_Room1_Text_ManyTrainersWhich::
    .string "There are many TRAINERS in here.\n"
    .string "Who do you want to tell me about?$"

SevenIsland_House_Room1_Text_NotFullFamecheckerForPerson::
    .string "Hmm… {STR_VAR_1}…?\p"
    .string "There's not enough information on\n"
    .string "{STR_VAR_1} for me to be able to\l"
    .string "truly tell how {STR_VAR_2} battles.\p"
    .string "Maybe once you've gathered more\n"
    .string "knowledge, you can show me again.$"

SevenIsland_House_Room1_Text_FullFamecheckerForPerson::
    .string "…!\p"
    .string "Yes, {STR_VAR_1} seems like exactly\n"
    .string "the type of battler I like to watch.$"

SevenIsland_House_Room1_Text_FirstFullFamecheckerPerson::
    .string "Let me tell you something. There's\n"
    .string "a hidden room in the basement.\p"
    .string "I once trained my POKéMON there and\n"
    .string "invited others down to battle too.\p"
    .string "I think I'm going to reopen the\n"
    .string "basement room and invite {STR_VAR_1}\l"
    .string "here to train.$"

SevenIsland_House_Room1_Text_CallSpearow::
    .string "SPEAROW!\n"
    .string "Come here please!$"

SevenIsland_House_Room1_Text_DeliverToLeader::
    .string "Take this invitation to {STR_VAR_1}\n"
    .string "in the {STR_VAR_3} GYM!$"

SevenIsland_House_Room1_Text_FirstTakeTime::
    .string "It'll take time for SPEAROW\n"
    .string "to return with a reply.\p"
    .string "You don't have to wait here\n"
    .string "with me. Come back later.\p"
    .string "In the mean time, I'll start\n"
    .string "renovating the basement.$"

SevenIsland_House_Room1_Text_TakeTime::
    .string "It'll take time for SPEAROW\n"
    .string "to return with a reply.\p"
    .string "You don't have to wait here\n"
    .string "with me. Come back later.$"

SevenIsland_House_Room1_Text_AlreadyShownPerson::
    .string "{STR_VAR_1}?\p"
    .string "We've already invited {STR_VAR_1}\n"
    .string "to train here with us.$"

SevenIsland_House_Room1_Text_SpearowNotBackYet::
    .string "SPEAROW hasn't come back yet.\n"
    .string "We'll have to wait a little longer\l"
    .string "for the reply to our invitation.$"

SevenIsland_House_Room1_Text_InviteBasementOpen::
    .string "I'm going to pen an invitation to\n"
    .string "{STR_VAR_1} and send it right now!$"

SevenIsland_House_Room1_Text_HeString::
    .string "he$"

SevenIsland_House_Room1_Text_SheString::
    .string "she$"

SevenIsland_House_Room1_Text_Spearow:: @ 818F32C
    .string "SPEAROW: Tetweet!$"

SevenIsland_House_Room1_Text_SlightBreezeAroundBox:: @ 81A0567
    .string "There is a slight breeze blowing\n"
    .string "around the box.$"

SevenIsland_House_Room1_Text_OldWomanNoVisitors::
    .string "Hello, {PLAYER}.\n"
    .string "Have you come to train?\p"
    .string "Right now no one is visiting\n"
    .string "in the basement, but if you've\l"
    .string "learned about more tough TRAINERS,\l"
    .string "I'd like to hear about them!$"

SevenIsland_House_Room1_Text_OldWomanOneVisitor::
    .string "Hello, {PLAYER}.\n"
    .string "Have you come to train?\p"
    .string "Right now {STR_VAR_1} is visiting\n"
    .string "in the basement.\p"
    .string "Or have you learned about\n"
    .string "more tough TRAINERS?$"

SevenIsland_House_Room1_Text_OldWomanMultiVisitors::
    .string "Hello, {PLAYER}.\n"
    .string "Have you come to train?\p"
    .string "Right now {STR_VAR_2} TRAINERS are\n"
    .string "visiting in the basement.\p"
    .string "Or have you learned about\n"
    .string "more tough TRAINERS?$"

SevenIsland_House_Room1_Text_OldWomanToldAllNoVisitors::
    .string "Hello, {PLAYER}.\n"
    .string "Have you come to train?\p"
    .string "Right now no one is visiting\n"
    .string "in the basement.\p"
    .string "Despite that, my heart is filled\n"
    .string "with joy at the battles I've\l"
    .string "watched thanks to you.$"

SevenIsland_House_Room1_Text_OldWomanToldAllOneVisitor::
    .string "Hello, {PLAYER}.\n"
    .string "Have you come to train?\p"
    .string "Right now {STR_VAR_1} is visiting\n"
    .string "in the basement.\p"
    .string "I can't thank you enough for\n"
    .string "filling my life with the joy of\l"
    .string "watching great battles again.$"

SevenIsland_House_Room1_Text_OldWomanToldAllMultiVisitors::
    .string "Hello, {PLAYER}.\n"
    .string "Have you come to train?\p"
    .string "Right now {STR_VAR_2} TRAINERS are\n"
    .string "visiting in the basement.\p"
    .string "I can't thank you enough for\n"
    .string "filling my life with the joy of\l"
    .string "watching great battles again.$"

SevenIsland_House_Room1_Text_NoShowFameChecker2::
    .string "Okay, {PLAYER}, let me know\n"
    .string "when you've learned more.$"

SevenIsland_House_Room1_Text_Two::
    .string "two$"

SevenIsland_House_Room1_Text_Three::
    .string "three$"

SevenIsland_House_Room1_Text_Four::
    .string "four$"

SevenIsland_House_Room1_Text_Five::
    .string "five$"

SevenIsland_House_Room1_Text_Six::
    .string "six$"

SevenIsland_House_Room1_Text_Seven::
    .string "seven$"
