BattleTower_BattleRoom_Text_19ACDC:: @ 819ACDC
	.string "We will restore your POKéMON to\n"
	.string "full health.$"

BattleTower_BattleRoom_Text_19AD09:: @ 819AD09
	.string "You will be facing opponent no. {STR_VAR_1}.\n"
	.string "Are you ready?$"

BattleTower_BattleRoom_Text_19AD3C:: @ 819AD3C
	.string "Would you like to save and\n"
	.string "quit the game?$"

BattleTower_BattleRoom_Text_19AD66:: @ 819AD66
	.string "Would you like to cancel your\n"
	.string "BATTLE ROOM challenge?$"

BattleTower_BattleRoom_Text_1C6CE1:: @ 81C6CE1
	.string "SAVING...\n"
	.string "DON'T TURN OFF THE POWER.$"

BattleTower_BattleRoom_Text_1C6D05:: @ 81C6D05
	.string "{PLAYER} saved the game.$"