Route9_Text_AliciaIntro:: @ 81847B7
    .string "You have POKéMON with you!\n"
    .string "You're mine!$"

Route9_Text_AliciaDefeat:: @ 81847DF
    .string "You deceived me…$"

Route9_Text_AliciaPostBattle:: @ 81847F0
    .string "The tunnel coming up is pitch-black\n"
    .string "inside.\p"
    .string "You'll need FLASH to get through\n"
    .string "there.$"

Route9_Text_ChrisIntro:: @ 8184844
    .string "Who's that walking there with those\n"
    .string "good-looking POKéMON?$"

Route9_Text_ChrisDefeat:: @ 818487E
    .string "Out like a light!$"

Route9_Text_ChrisPostBattle:: @ 8184890
    .string "Keep walking!$"

Route9_Text_DrewIntro:: @ 818489E
    .string "I'm taking the ROCK TUNNEL to\n"
    .string "go to LAVENDER…$"

Route9_Text_DrewDefeat:: @ 81848CC
    .string "Can't measure up…$"

Route9_Text_DrewPostBattle:: @ 81848DE
    .string "Are you off to ROCK TUNNEL, too?$"

Route9_Text_CaitlinIntro:: @ 81848FF
    .string "Don't you dare patronize me!$"

Route9_Text_CaitlinDefeat:: @ 818491C
    .string "No!\n"
    .string "You're too much.$"

Route9_Text_CaitlinPostBattle:: @ 8184931
    .string "You're obviously talented.\n"
    .string "Good luck to you!$"

Route9_Text_JeremyIntro:: @ 818495E
    .string "Bwahaha!\n"
    .string "Great! I was bored, eh!$"

Route9_Text_JeremyDefeat:: @ 818497F
    .string "Keep it coming, eh!\p"
    .string "Oh wait.\n"
    .string "I'm out of POKéMON!$"

Route9_Text_JeremyPostBattle:: @ 81849B0
    .string "You sure had guts standing up to\n"
    .string "me there, eh?$"

Route9_Text_BriceIntro:: @ 81849DF
    .string "Hahaha!\n"
    .string "Aren't you a little toughie!$"

Route9_Text_BriceDefeat:: @ 8184A04
    .string "What's that?$"

Route9_Text_BricePostBattle:: @ 8184A11
    .string "Hahaha!\n"
    .string "Kids should be tough!$"

Route9_Text_BrentIntro:: @ 8184A2F
    .string "I got up early every day to raise\n"
    .string "my POKéMON from cocoons!$"

Route9_Text_BrentDefeat:: @ 8184A6A
    .string "WHAT?\p"
    .string "What a total waste of time!$"

Route9_Text_BrentPostBattle:: @ 8184A8C
    .string "I have to collect more than bugs\n"
    .string "to get stronger…$"

Route9_Text_AlanIntro:: @ 8184ABE
    .string "Hahahaha!\n"
    .string "Bring it on!$"

Route9_Text_AlanDefeat:: @ 8184AD5
    .string "Hahahaha!\n"
    .string "You beat me fair!$"

Route9_Text_AlanPostBattle:: @ 8184AF1
    .string "Hahahaha!\n"
    .string "Us hearty guys always laugh!$"

Route9_Text_ConnerIntro:: @ 8184B18
    .string "Go, my super BUG POKéMON!$"

Route9_Text_ConnerDefeat:: @ 8184B32
    .string "My bugs…$"

Route9_Text_ConnerPostBattle:: @ 8184B3B
    .string "If you don't like BUG POKéMON,\n"
    .string "you bug me!$"

Route9_Text_RouteSign:: @ 8184B66
    .string "ROUTE 9\n"
    .string "CERULEAN CITY - ROCK TUNNEL$"

Route9_Text_Bulbasaur::
    .string "BULBASAUR: …$"

Route9_Text_BulbasaurWeak::
    .string "BULBASAUR looks very weak…$"

Route9_Text_FoundInjuredBulbasaur::
    .string "I take care of injured POKéMON.\p"
    .string "This BULBASAUR needs\n"
    .string "medicine, however.\p"
    .string "A SUPER POTION would\n" 
    .string "be just what we need…$"

Route9_Text_WantThisBulbasaur::
    .string "You're a TRAINER, aren't you?\p"
    .string "I take care of injured POKéMON.\p"
    .string "This BULBASAUR needs\n"
    .string "medicine, and quickly.\p"
    .string "If you treat this POKéMON,\n"
    .string "it will surely accept you as\p"
    .string "its TRAINER.\p"
    .string "Do you have a SUPER POTION\n"
    .string "to spare?$"

Route9_Text_Oh::
    .string "But… poor BULBASAUR…$"

Route9_Text_BulbasaurHealed::
   .string "BULBASAUR is eager to join you!\p"
   .string "Now, administer the medicine.$"

Route9_Text_ObtainedBulbasaurFromLady::
    .string "{PLAYER} obtained a BULBASAUR!$"

Route9_Text_TreatHimRight::
    .string "OK! Please treat BULBASAUR right!$"

Route9_Text_HowIsBulbasaur::
    .string "Hello! How is BULBASAUR doing?$"