SafariZone_NorthWest_MapScripts::
	.byte 0

SafariZone_NorthWest_EventScript_RestHouseSign::
	msgbox SafariZone_NorthWest_Text_RestHouseSign, MSGBOX_SIGN
	end

SafariZone_NorthWest_Text_RestHouseSign::
	.string "REST HOUSE\n"
	.string "Fill up on steps inside!$"

SafariZone_NorthWest_EventScript_AreaSign::
	msgbox SafariZone_NorthWest_Text_AreaSign, MSGBOX_SIGN
	end

SafariZone_NorthWest_Text_AreaSign::
	.string "AREA 4$"