BattleTower_Lobby_Text_199F2C:: @ 8199F2C
	.string "Welcome to the BATTLE TOWER!\p"
	.string "Please register with me to enter\n"
	.string "a BATTLE ROOM.$"

BattleTower_Lobby_Text_199F79:: @ 8199F79
	.string "Would you like to make a\n"
	.string "BATTLE ROOM challenge?$"

BattleTower_Lobby_Text_199FA9:: @ 8199FA9
	.string "We'll be looking forward to your\n"
	.string "next challenge.$"

BattleTower_Lobby_Text_199FDA:: @ 8199FDA
	.string "Before entering a BATTLE ROOM\n"
	.string "your progress must be saved.\lIs that okay?$"

BattleTower_Lobby_Text_19A024:: @ 819A024
	.string "There are two BATTLE ROOMS,\n"
	.string "Level 50 and Open Level.\l"
	.string "Which would you like to challenge?$"

BattleTower_Lobby_Text_19A07B:: @ 819A07B
	.string "Please select the POKéMON you wish\n"
	.string "to enter.$"

BattleTower_Lobby_Text_19A0A8:: @ 819A0A8
	.string "I'll direct you to your BATTLE\nROOM now.$"

BattleTower_Lobby_Text_19A0D1:: @ 819A0D1
	.string "The BATTLE TOWER is a facility made\n"
	.string "especially for POKéMON battles.\p"
	.string "Within the TOWER are many\nBATTLE ROOMS.\p"
	.string "The BATTLE ROOMs come in two styles,\n"
	.string "Level 50 and Open Level.\p"
	.string "The level 50 BATTLE ROOMS are\n"
	.string "open to POKéMON up to and\l"
	.string "including Level 50.\p"
	.string "No other TRAINERS in the room\n"
	.string "will have POKéMON below Level 50.\p"
	.string "The Open Level BATTLE ROOMS\n"
	.string "are open to POKéMON of all levels.\p"
	.string "The levels of your opponents will\n"
	.string "be adjusted to match the levels\l"
	.string "of your POKéMON.\p"
	.string "However, no other TRAINERS in the\n"
	.string "room will have POKéMON that are\lbelow Level 60.\p"
	.string "In each BATTLE ROOM, seven\n"
	.string "TRAINERS await your challenge.\p"
	.string "Beat all seven, and you will be\n"
	.string "rewarded with a fabulous prize.\p"
	.string "You may also take a break from your\n"
	.string "challenge by saving your progress.\p"
	.string "Make sure you save properly\n"
	.string "or you won't be able to\lresume your challenge.$"

BattleTower_Lobby_Text_19A249:: @ 819A249
	.string "Excuse me!\p"
	.string "You don't have three eligible\nPOKéMON.\p"
	.string "You must have three different\n"
	.string "POKéMON of Level 50 or less\lto enter.\p"
	.string "They also must be holding different\n"
	.string "kinds of items.\p"
	.string "EGGS are ineligible.\p"
	.string "Please come see me when\nyou are ready.$"

BattleTower_Lobby_Text_19A32D:: @ 819A32D
	.string "Excuse me!\p"
	.string "You don't have three eligible\nPOKéMON.\p"
	.string "You must have three different\nPOKéMON "
	.string "to enter.\p"
	.string "They also must be holding different\n"
	.string "kinds of items.\p"
	.string "EGGS are ineligible.\p"
	.string "Please come see me when\nyou are ready.$"

BattleTower_Lobby_Text_19A3FD:: @ 819A3FD
	.string "Excuse me!\p"
	.string "You didn't save before you quit your\n"
	.string "challenge last time.\p"
	.string "Because of that, your challenge so\n"
	.string "far has been disqualified. Sorry!$"

BattleTower_Lobby_Text_19A487:: @ 819A487
	.string "Congratulations!\n"
	.string "You've beaten all seven TRAINERS!\p"
	.string "$"

BattleTower_Lobby_Text_19A4BB:: @ 819A4BB
	.string "For beating your challenge, you\n"
	.string "have earned this fabulous prize!\p"
	.string "$"

BattleTower_Lobby_Text_19A506:: @ 819A506
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"

BattleTower_Lobby_Text_19A520:: @ 819A520
	.string "Oh, your BAG appears to be full.\p"
	.string "Please make room in your BAG,\n"
	.string "then come see me.$"

BattleTower_Lobby_Text_19A571:: @ 819A571
	.string "Thank you for playing!\p"
	.string "$"

BattleTower_Lobby_Text_19A589:: @ 819A589
	.string "Your record will be saved.\n"
	.string "Please wait.$"

BattleTower_Lobby_Text_19A5B1:: @ 819A5B1
	.string "We've been waiting for you!\p"
	.string "$"

BattleTower_Lobby_Text_19A5CE:: @ 819A5CE
	.string "Before entering a BATTLE ROOM,\n"
	.string "your progress will be saved.\lPlease wait.$"

BattleTower_Lobby_Text_19A617:: @ 819A617
	.string "You're finally about to face the\n"
	.string "50th TRAINER.\p"
	.string "From here on, every time you beat\n"
	.string "seven TRAINERS in a row, your\l"
	.string "POKéMON will receive a\lcommemorative RIBBON.\p"
	.string "Good luck!$"

BattleTower_Lobby_Text_19A6BE:: @ 819A6BE
	.string "Here are some RIBBONS for beating\n"
	.string "seven tough TRAINERS in a row.\p"
	.string "{COLOR DARK_GRAY}{PLAYER} received some RIBBONS!$"

BattleTower_Lobby_Text_19A719:: @ 819A719
	.string "{COLOR DARK_GRAY}{PLAYER} put the RIBBONS on the\n"
	.string "challenger POKéMON.$"

BattleTower_Lobby_Text_19A747:: @ 819A747
    .string "Hello, hello!\n"
    .string "Where are you from, TRAINER?\p"
    .string "…\p"
    .string "KANTO? PALLET TOWN?\n"
    .string "That's quite a ways away!$"

BattleTower_Lobby_Text_19A8AE:: @ 819A8AE
	.string "The number of matches you win in\n"
	.string "a row is recorded.\p"
	.string "The record is posted beside the\n"
	.string "registration counter.$"

BattleTower_Lobby_Text_19A946:: @ 819A946
	.string "Once you're in the BATTLE TOWER,\n"
	.string "you can't leave until you lose or\l"
	.string "beat seven TRAINERS in a row.\p"
	.string "You'd best be certain that you're\n"
	.string "up to the challenge.$"

BattleTower_Lobby_Text_Scott28Wins::
	.string "SCOTT: I heard about you!\n"
	.string "How you ruled the BATTLE TOWER!\l"
	.string "You beat 28 TRAINERS in a row?\p"
	.string "That's fantastic!\n"
	.string "I want you to have this!$"

BattleTower_Lobby_Text_ScottExplainAuroraTicket::
	.string "Bring that ticket to your\n"
	.string "friend at the VERMILION HARBOR.\p"
	.string "He'll be able to take you to a\n"
	.string "small island south of SIX ISLAND.\p"
	.string "There's a strange stone and\n"
	.string "nothing else there.\p"
	.string "It's nice and private, though,\n"
	.string "so it's a good vacation spot!$"

BattleTower_Lobby_Text_Scott56Wins::
	.string "SCOTT: Oh my! I heard about you!\n"
	.string "How you crushed the BATTLE TOWER!\p"
	.string "You beat 56 TRAINERS in a row?\p"
	.string "That's ridiculously spectacular!\n"
	.string "You've got to have this!$"

BattleTower_Lobby_Text_ScottExplainEonTicket::
	.string "Bring that ticket to your\n"
	.string "friend at the VERMILION HARBOR.\p"
	.string "He'll be able to take you to an\n"
	.string "island that's not far from here.\p"
	.string "There's a nice little grove there,\n"
	.string "perfect for a relaxing picnic\l"
	.string "when you're not training.$"

BattleTower_Lobby_Text_ScottGaveAuroraTicket::
	.string "I'll be expecting to hear even\n"
	.string "greater things about you now!$"

BattleTower_Lobby_Text_ScottGaveEonTicket::
	.string "This BATTLE TOWER has been a\n"
	.string "huge success but…\p"
	.string "Perhaps it's time to push\n"
	.string "this project to a new frontier…$"
		