LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere:: @ 819358E
    .string "I recently moved to this town.\p"
    .string "I hear that MR. FUJI's not from\n"
    .string "these parts originally, either.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo:: @ 81935ED
    .string "That's odd, MR. FUJI isn't here.\n"
    .string "Where'd he go?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother:: @ 819361D
    .string "MR. FUJI had been praying alone\n"
    .string "for CUBONE's mother.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons:: @ 8193652
    .string "This is really MR. FUJI's house.\p"
    .string "He's really kind.\p"
    .string "He looks after abandoned and\n"
    .string "orphaned POKéMON.$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug:: @ 81936B4
    .string "It's so warm!\n"
    .string "POKéMON are so nice to hug.$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino:: @ 81936DE
    .string "NIDORINO: Gaoo!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck:: @ 81936EE
    .string "PSYDUCK: Gwappa!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis:: @ 81936FF
    .string "MR. FUJI: {PLAYER}…\p"
    .string "Your POKéDEX quest is one that\n"
    .string "requires strong dedication.\p"
    .string "Without deep love for POKéMON,\n"
    .string "your quest may fail.\p"
    .string "I'm not sure if this will help you,\n"
    .string "but I'd like you to have it.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji:: @ 81937BD
    .string "{PLAYER} received a POKé FLUTE\n"
    .string "from MR. FUJI.$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute:: @ 81937E5
    .string "Upon hearing the POKé FLUTE,\n"
    .string "sleeping POKéMON will spring awake.\p"
    .string "Try using it on POKéMON that are\n"
    .string "sleeping obstacles.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis:: @ 819385B
    .string "You must make room for this!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou:: @ 8193878
    .string "MR. FUJI: Has my POKé FLUTE\n"
    .string "helped you?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped:: @ 81938A0
    .string "POKéMON FAN MAGAZINE\n"
    .string "Monthly Grand Prize Drawing!\p"
    .string "The application form is…\p"
    .string "Gone! It's been clipped out.\n"
    .string "Someone must have applied already.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf:: @ 819392B
    .string "POKéMON magazines line the shelf.\p"
    .string "POKéMON INSIDER…\p"
    .string "POKéMON FAN…$"

LavenderTown_VolunteerPokemonHouse_Text_FindFarawayIsland::
    .string "MR. FUJI: Have you found the\n"
    .string "island on my OLD SEA MAP?$"

LavenderTown_VolunteerPokemonHouse_Text_FoundMew::
    .string "MR. FUJI: {PLAYER}!\p"
    .string "Did my OLD SEA MAP help you?\n"
    .string "Did you find that POKéMON?$"

LavenderTown_VolunteerPokemonHouse_Text_DefeatedMew::
    .string "Ah, so the poor thing fled\n"
    .string "the moment it saw you.\p"
    .string "Perhaps some wrongs can never\n"
    .string "be righted…\p"
    .string "I must thank you for your kind\n"
    .string "concern anyway, {PLAYER}.\p"
    .string "Maybe that POKéMON will return\n"
    .string "someday…$"

LavenderTown_VolunteerPokemonHouse_Text_CaughtMew::
    .string "You were able to befriend it?\n"
    .string "Even after all it's been through?\p"
    .string "Thank you, {PLAYER}!\p"
    .string "You have eased my mind and\n"
    .string "calmed that POKéMON's spirit.\p"
    .string "I'm sure the both of you will\n"
    .string "become even closer with time.$"

LavenderTown_VolunteerPokemonHouse_Text_AnsweredNo::
    .string "The OLD SEA MAP can show you\n"
    .string "how to get to the island.\p"
    .string "A sailor should be able to\n"
    .string "read it and take you there.\p"
    .string "You know someone with a boat,\n"
    .string "Don't you, {PLAYER}?$"

LavenderTown_VolunteerPokemonHouse_Text_NotEncounteredMew::
    .string "Ah, so you haven't found the\n"
    .string "POKéMON there yet.\p"
    .string "If I remember correctly, it\n"
    .string "enjoys playing in the long grass.$"

LavenderTown_VolunteerPokemonHouse_Text_HowAreYouAndMew:: @ 8193878
    .string "MR. FUJI: {PLAYER}! Welcome!\n"
    .string "How are you and MEW doing?$"

