MtMoon_Square_Text_Sign::
    .string "This is MT. MOON SQUARE.\p"
	.string "Please don't litter. Put\n"
	.string "trash where it belongs!$"

MtMoon_Square_Text_MudkipNoise::
    .string "Mrrfrk!!$"

MtMoon_Square_Text_MudkipAngryFood::
    .string "You stepped on MUDKIP's!\n"
	.string "SITRUS BERRY!\p"
	.string "It probably will stay angry with\n"
	.string "you unless you give it another\p"
	.string "SITRUS BERRY.\p"
	.string "Give MUDKIP a SITRUS BERRY?$"
	
MtMoon_Square_Text_MudkipStillAngry::
	.string "MUDKIP remains  upset with you!$"

MtMoon_Square_Text_MudkipHappyJoin
    .string "MUDKIP is no longer angry!\p"
	.string "It seems to really appreciate your\n"
	.string "kind gesture and wants you as its.\p"
	.string "TRAINER.\p"
	.string "Do you want to bring MUDKIP along?\p"

MtMoon_Square_Text_ObtainedMudkip::
    .string "{PLAYER} obtained a MUDKIP!$"
