SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale:: @ 819AC60
    .string "{PLAYER}: Hi!\n"
    .string "Do you like POKéMON?\p"
    .string "{PLAYER}: Uh, no, I just asked you.\p"
    .string "{PLAYER}: Huh?\n"
    .string "You're strange!\p"
    .string "COPYCAT: Hmm? Quit mimicking?\n"
    .string "But, that's my favorite hobby!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale:: @ 819ACF1
    .string "{PLAYER}: Hi.\n"
    .string "You must like POKéMON.\p"
    .string "{PLAYER}: No, not me.\n"
    .string "I asked you.\p"
    .string "{PLAYER}: Pardon?\n"
    .string "You're weird!\l"
    .string " \l"
    .string "COPYCAT: Hmm? Quit mimicking?\l"
    .string "But that's my favorite hobby!$"

Text_MimicTeach:: @ 819AD85
    .string "Oh wow!\n"
    .string "A POKé DOLL!\p"
    .string "For me?\n"
    .string "Thank you!\p"
    .string "You know what?\n"
    .string "I can teach the move MIMIC.$"

Text_MimicDeclined:: @ 819ADD8
    .string "Don't you like MIMIC?$"

Text_MimicWhichMon:: @ 819ADEE
    .string "I really love MIMIC!\n"
    .string "Who's going to learn it?$"

Text_MimicTaughtMale:: @ 819AE1C
    .string "{PLAYER}: Hi!\n"
    .string "Thanks for earlier!\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it that fun to mimic my\n"
    .string "every move?\p"
    .string "COPYCAT: You bet!\n"
    .string "It's a scream!$"

Text_MimicTaughtFemale:: @ 819AE90
    .string "{PLAYER}: Hi!\n"
    .string "Thanks for what you did for us.\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it really that fun to\n"
    .string "copy what I say and do?\p"
    .string "COPYCAT: You bet!\n"
    .string "It's a scream!$"

Text_MimicReteach::
    .string "{PLAYER}: Hi!\n"
    .string "Could you teach us MIMIC again?\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it that fun to copy my\n"
    .string "every word?\p"
    .string "COPYCAT: Absolutely!\n"
    .string "It's a scream!\p"
    .string "I can reteach MIMIC if you'll give\n"
    .string "me ¥5000 for more dolls!$"

Text_MimicReteach2::
    .string "Is that okay?\n"
    .string "Should I mimic teaching MIMIC?$"

Text_MimicNotEnoughMoney::
    .string "{PLAYER}: ¥5000?\n"
    .string "But a POKé DOLL only costs ¥1000!\p"
    .string "I don't have enough money for\n"
    .string "that right now…\p"
    .string "COPYCAT: I want to buy five\n"
    .string "POKé DOLLS! So I need ¥5000!\p"
    .string "I'll mimic teaching MIMIC to\n"
    .string "your POKéMON when you have it!$"

Text_MimicTaughtMale2::
    .string "{PLAYER}: Okay!\n"
    .string "Thanks for that!\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it that fun to mimic my\n"
    .string "every move?\p"
    .string "COPYCAT: You bet!\n"
    .string "It's a scream!$"

Text_MimicTaughtFemale2:: @ 819AE90
    .string "{PLAYER}: Okay!\n"
    .string "Thanks for what you did for us.\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it really that fun to\n"
    .string "copy what I say and do?\p"
    .string "COPYCAT: You bet!\n"
    .string "It's a scream!$"

SaffronCity_CopycatsHouse_2F_Text_Doduo:: @ 819B030
    .string "DODUO: Giiih!\p"
    .string "PRETTY MIRROR LOOK AT ME,\n"
    .string "SEE HOW PRETTY I CAN BE?$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll:: @ 819B071
    .string "This is a rare POKéMON!\n"
    .string "Huh? It's only a doll!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket:: @ 819B0A0
    .string "A game with MARIO wearing a bucket\n"
    .string "on his head!$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets:: @ 819B0D0
    .string "…\p"
    .string "My Secrets!\p"
    .string "Skill: Mimicry!\n"
    .string "Hobby: Collecting dolls!\l"
    .string "Favorite POKéMON: CLEFAIRY!$"

