Text_MimicTeach::
    .string "Oh wow!\n"
    .string "A POKé DOLL!\p"
    .string "For me?\n"
    .string "Thank you!\p"
    .string "You know what?\n"
    .string "I can teach the move MIMIC.$"

Text_MimicDeclined::
    .string "Don't you like MIMIC?$"

Text_MimicWhichMon::
    .string "I really love MIMIC!\n"
    .string "Who's going to learn it?$"

Text_MimicTaughtMale::
    .string "{PLAYER}: Hi!\n"
    .string "Thanks for earlier!\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it that fun to mimic my\n"
    .string "every move?\p"
    .string "COPYCAT: You bet!\n"
    .string "It's a scream!$"

Text_MimicTaughtFemale::
    .string "{PLAYER}: Hi!\n"
    .string "Thanks for what you did for us.\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it really that fun to\n"
    .string "copy what I say and do?\p"
    .string "COPYCAT: You bet!\n"
    .string "It's a scream!$"

Text_MimicReteach::
    .string "{PLAYER}: Could you teach us\nMIMIC again?\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it that fun to copy my\n"
    .string "every word?\p"
    .string "COPYCAT: Absolutely!\n"
    .string "It's a scream!\p"
    .string "I can reteach MIMIC if you'll give\n"
    .string "me ¥5000 for more dolls!$"

Text_MimicReteach2::
    .string "Is that okay?\n"
    .string "Should I mimic teaching MIMIC?$"

Text_MimicNotEnoughMoney::
    .string "{PLAYER}: ¥5000?\n"
    .string "But a POKé DOLL only costs ¥1000!\p"
    .string "I don't have enough money for\n"
    .string "that right now…\p"
    .string "COPYCAT: I'm saving up for the big\n"
    .string "POKé DOLLS! So I need ¥5000!\p"
    .string "I'll mimic teaching MIMIC to\n"
    .string "your POKéMON when you have it!$"

Text_MimicTaughtMale2::
    .string "{PLAYER}: Okay!\n"
    .string "Thanks for that!\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it that fun to mimic my\n"
    .string "every move?\p"
    .string "COPYCAT: You bet!\n"
    .string "It's a scream!$"

Text_MimicTaughtFemale2::
    .string "{PLAYER}: Okay!\n"
    .string "Thanks for what you did for us.\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it really that fun to\n"
    .string "copy what I say and do?\p"
    .string "COPYCAT: You bet!\n"
    .string "It's a scream!$"
