Mt_Battle_Lobby_MapScripts::
	.byte 0

Mt_Battle_Lobby_EventScript_CooltrainerM::
	msgbox Mt_Battle_Lobby_Text_CooltrainerM, MSGBOX_NPC
	end

Mt_Battle_Lobby_Text_CooltrainerM:
	.string "I'm going to collect POKé COUPONS\n"
	.string "so I can get some new moves for my\l"
	.string "POKéMON.\p"
	.string "See that man in white sitting on the\n"
	.string "bench? He teaches POKéMON moves in\l"
	.string "exchange for POKé COUPONS.$"

Mt_Battle_Lobby_EventScript_CooltrainerF::
	msgbox Mt_Battle_Lobby_Text_CooltrainerF, MSGBOX_NPC
	end

Mt_Battle_Lobby_Text_CooltrainerF:
	.string "You can earn POKé COUPONS even\n"
	.string "while you're training.\l"
	.string "MT. BATTLE is a cool place!$"