CeruleanCity_BikeShop_Text_WelcomeToBikeShop::
    .string "Hi!\n"
    .string "Welcome to our BIKE SHOP.\p"
    .string "Have we got just the BIKE for\n"
    .string "you!$"

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt::
    .string "Sorry!\n"
    .string "You can't afford it!$"

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo::
    .string "Oh, that's…\p"
    .string "A BIKE VOUCHER!\p"
    .string "Okay!\n"
    .string "Here you go!$"

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle::
    .string "{PLAYER} exchanged the\n"
    .string "BIKE VOUCHER for a BICYCLE.$"

CeruleanCity_BikeShop_Text_ThankYouComeAgain::
    .string "Thank you!\n"
    .string "Come back again sometime!$"

CeruleanCity_BikeShop_Text_ExplainBicycleGears::
    .string "This BICYCLE has two gears.\n"
    .string "Press the B Button to switch them\l"
    .string "for more control of your speed!$"

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle::
    .string "How do you like your new BICYCLE?\n"
    .string "Do you like how it rides?\p"
    .string "You can take it out on CYCLING\n"
    .string "ROAD and even into caves!\p"
    .string "You can switch gears for more\n"
    .string "speed too with the B Button!$"

CeruleanCity_BikeShop_Text_MakeRoomForBicycle::
    .string "You better make room for your\n"
    .string "BICYCLE!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe::
    .string "A plain city bike is good enough\n"
    .string "for me.\p"
    .string "After all, you can't put a shopping\n"
    .string "basket on a mountain bike.$"

CeruleanCity_BikeShop_Text_BikesCoolButExpensive::
    .string "These bikes are cool, but they're\n"
    .string "way expensive!$"

CeruleanCity_BikeShop_Text_WowYourBikeIsCool::
    .string "Wow.\n"
    .string "Your BIKE is really cool!$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle::
    .string "A shiny new BICYCLE!$"

