
BattleTower_Outside_Text_199C6F:: @ 8199C6F
	.string "BATTLE TOWER\n"
	.string "“Win it all and be the best!”$"

BattleTower_Outside_Text_199CA4:: @ 8199CA4
	.string "This is the BATTLE TOWER.\p"
	.string "TRAINERS bring their best POKéMON\n"
	.string "for elimination-style matches.$"

BattleTower_Outside_Text_199E9C:: @ 8199E9C
	.string "I'm not leaving until I've beaten\n"
	.string "35 TRAINERS in a row!$"

BattleTower_Outside_Text_199ED4:: @ 8199ED4
	.string "Gee, there're a lot of\n"
	.string "tough-looking TRAINERS here.\l"
	.string "I'm not good enough to enter yet…$"
